"""
MediaAsset model for CineCraft.
Represents uploaded or generated media files.
"""
from sqlalchemy import Column, Integer, String, BigInteger, ForeignKey, Enum as SQLEnum, JSON, DateTime
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.models.base import BaseModel


class MediaType(str, enum.Enum):
    """Media asset type enumeration."""
    IMAGE = "image"
    AUDIO = "audio"
    VIDEO = "video"
    MUSIC = "music"
    SUBTITLE = "subtitle"
    OTHER = "other"


class MediaAsset(BaseModel):
    """
    MediaAsset model.

    Represents a media file (image, audio, video, etc.) that is either
    uploaded by user or generated by AI providers.
    """
    __tablename__ = "media_assets"

    # Ownership
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), nullable=True, index=True)
    scene_id = Column(Integer, ForeignKey("scenes.id", ondelete="CASCADE"), nullable=True, index=True)

    # File information
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255), nullable=True)
    file_path = Column(String(500), nullable=False)  # Path in storage
    file_size = Column(BigInteger, nullable=False)  # Size in bytes
    mime_type = Column(String(100), nullable=False)
    media_type = Column(SQLEnum(MediaType), nullable=False, index=True)

    # Storage information
    storage_provider = Column(String(50), nullable=False, default="local")  # 'local' or 's3'
    storage_bucket = Column(String(255), nullable=True)  # For S3
    storage_region = Column(String(50), nullable=True)  # For S3

    # Public URL (if accessible)
    url = Column(String(500), nullable=True)
    cdn_url = Column(String(500), nullable=True)  # CDN URL if available

    # Media metadata
    width = Column(Integer, nullable=True)  # For images/videos
    height = Column(Integer, nullable=True)  # For images/videos
    duration = Column(Integer, nullable=True)  # For audio/video (in seconds)
    media_metadata = Column(JSON, nullable=False, default=dict)
    # Example media_metadata:
    # {
    #   "format": "png",
    #   "color_space": "RGB",
    #   "bitrate": 192000,
    #   "sample_rate": 44100,
    #   "generated_by": "dalle",
    #   "generation_prompt": "A serene forest at dawn"
    # }

    # Generation information (if AI-generated)
    is_generated = Column(Integer, nullable=False, default=0)  # Boolean as int for SQLite
    generation_provider = Column(String(50), nullable=True)  # e.g., "dalle", "elevenlabs"
    generation_prompt = Column(String(1000), nullable=True)
    generation_cost = Column(Integer, nullable=True)  # Cost in cents

    # Timestamps
    uploaded_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)  # For temporary files

    # Relationships
    user = relationship("User", back_populates="media_assets")
    project = relationship("Project", back_populates="media_assets")
    scene = relationship("Scene", back_populates="media_assets")

    def __repr__(self):
        return f"<MediaAsset(id={self.id}, filename='{self.filename}', type='{self.media_type}')>"

    @property
    def file_size_mb(self) -> float:
        """Get file size in megabytes."""
        return round(self.file_size / (1024 * 1024), 2)

    @property
    def is_image(self) -> bool:
        """Check if asset is an image."""
        return self.media_type == MediaType.IMAGE

    @property
    def is_audio(self) -> bool:
        """Check if asset is audio."""
        return self.media_type == MediaType.AUDIO

    @property
    def is_video(self) -> bool:
        """Check if asset is video."""
        return self.media_type == MediaType.VIDEO

    @property
    def is_expired(self) -> bool:
        """Check if asset has expired."""
        if not self.expires_at:
            return False
        return datetime.utcnow() > self.expires_at

    def get_full_path(self, base_path: str = None) -> str:
        """
        Get full filesystem path.

        Args:
            base_path: Base storage path (for local storage)

        Returns:
            Full path to file
        """
        if self.storage_provider == "local" and base_path:
            return f"{base_path}/{self.file_path}"
        return self.file_path


# Add relationships to other models
from app.models.user import User
from app.models.project import Project
from app.models.scene import Scene

User.media_assets = relationship(
    "MediaAsset",
    back_populates="user",
    cascade="all, delete-orphan"
)

Project.media_assets = relationship(
    "MediaAsset",
    back_populates="project",
    cascade="all, delete-orphan"
)

Scene.media_assets = relationship(
    "MediaAsset",
    back_populates="scene",
    cascade="all, delete-orphan"
)
