"""
Project model for CineCraft.
Represents a video project created by a user.
"""
from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, JSON, Enum as SQLEnum
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.models.base import BaseModel


class ProjectStatus(str, enum.Enum):
    """Project status enumeration."""
    DRAFT = "draft"
    GENERATING = "generating"
    READY = "ready"
    RENDERING = "rendering"
    COMPLETED = "completed"
    FAILED = "failed"


class Project(BaseModel):
    """
    Project model.

    Represents a video project that contains story, scenes, and generated media.
    """
    __tablename__ = "projects"

    # Basic information
    title = Column(String(255), nullable=False, index=True)
    description = Column(Text, nullable=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Project status
    status = Column(
        SQLEnum(ProjectStatus),
        default=ProjectStatus.DRAFT,
        nullable=False,
        index=True
    )

    # Story content (generated by AI)
    story = Column(Text, nullable=True)
    story_prompt = Column(Text, nullable=True)  # Original user prompt

    # Project metadata
    project_metadata = Column(JSON, nullable=False, default=dict)
    # Example project_metadata:
    # {
    #   "genre": "fantasy",
    #   "tone": "dramatic",
    #   "target_audience": "adult",
    #   "duration_target": 120,
    #   "ai_model_used": "claude-3-opus"
    # }

    # Video settings
    video_duration = Column(Integer, nullable=True)  # Target duration in seconds
    language = Column(String(20), nullable=True, default="english")
    video_length = Column(String(20), nullable=True, default="short")
    video_url = Column(String(500), nullable=True)  # Final rendered video URL
    thumbnail_url = Column(String(500), nullable=True)

    # Statistics
    views_count = Column(Integer, default=0, nullable=False)
    likes_count = Column(Integer, default=0, nullable=False)

    # Visibility
    is_public = Column(Boolean, default=False, nullable=False)
    is_archived = Column(Boolean, default=False, nullable=False)

    # Timestamps for tracking generation progress
    story_generated_at = Column(DateTime, nullable=True)
    scenes_generated_at = Column(DateTime, nullable=True)
    media_generated_at = Column(DateTime, nullable=True)
    rendered_at = Column(DateTime, nullable=True)

    # Relationships
    user = relationship("User", back_populates="projects")
    scenes = relationship(
        "Scene",
        back_populates="project",
        cascade="all, delete-orphan",
        order_by="Scene.sequence_number"
    )
    characters = relationship(
        "Character",
        back_populates="project",
        cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<Project(id={self.id}, title='{self.title}', status='{self.status}')>"

    @property
    def scene_count(self) -> int:
        """Get the number of scenes in this project."""
        return len(self.scenes) if self.scenes else 0

    @property
    def is_complete(self) -> bool:
        """Check if project has completed all generation steps."""
        return self.status == ProjectStatus.COMPLETED

    @property
    def can_render(self) -> bool:
        """Check if project is ready for rendering."""
        return (
            self.status == ProjectStatus.READY and
            self.story is not None and
            self.scene_count > 0 and
            self.media_generated_at is not None
        )

    def update_status(self, new_status: ProjectStatus):
        """Update project status and set timestamp."""
        self.status = new_status
        self.updated_at = datetime.utcnow()

        if new_status == ProjectStatus.COMPLETED and self.rendered_at is None:
            self.rendered_at = datetime.utcnow()


# Add relationship to User model
from app.models.user import User
User.projects = relationship(
    "Project",
    back_populates="user",
    cascade="all, delete-orphan",
    order_by="Project.created_at.desc()"
)
