"""add_documentary_fields

Revision ID: ef964ec3498f
Revises: 
Create Date: 2026-03-29 13:25:05.416712+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef964ec3498f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('video_length', sa.String(length=20), nullable=True))
    op.add_column('scenes', sa.Column('video_prompt', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('emotion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'emotion')
    op.drop_column('scenes', 'video_prompt')
    op.drop_column('projects', 'video_length')
    op.drop_column('projects', 'language')
    # ### end Alembic commands ###
